#####################################################################
# Lilith Private LTE - UE Configuration: User A (111)
# IMSI: 001010000000001
#####################################################################

[usim]
# USIM configuration
mode = soft
imsi = 001010000000001
imei = 353490069873190
k = 00112233445566778899AABBCCDDEEFF
opc = 000102030405060708090A0B0C0D0E0F
amf = 0x9001
duplex_mode = FDD
# Use OPc instead of OP
using_op = 0

[rrc]
# RRC configuration
release = 13
cell_select_win = 3

[nas]
# NAS configuration
apn = lilith
apn_protocol = ipv4
force_imsi_attach = true

# SMS configuration
sms_service_center = +001111111
sms_over_nas = true

[phy]
# Physical layer configuration
nof_rx_antennas = 1

[rf]
# RF frontend configuration
device_name = zmq
device_args = "tx_port=tcp://*:2101,rx_port=tcp://localhost:2000,id=ue-usera,broker_addr=tcp://172.20.0.100:5555"
tx_freq = 2680e6
rx_freq = 2560e6
tx_gain = 70
rx_gain = 30
srate = 11.52e6

[log]
# Logging
filename = /var/log/srsran/ue_usera.log
file_max_size = -1
all_level = info
rrc_level = debug
nas_level = debug

[gw]
# Gateway configuration
ipnet = 10.45.0.0/16

[general]
# General settings
single_tx = true

[sim]
# Simulation settings
enable_mib_decode = true
enable_sib_decode = true

[sensors]
# Sensor measurements
enable = false
